### ISSUE TITLE
about new balancing.

### ISSUE THREAD

**Issue by skullbe** [Wolferos/Hearts-of-Iron-IV-The-Great-War#151]
Central powers got buff in lastest update, but they are still weak. they cant conquer benelux even luxemburg. so i think there are some problems.

1.too strong trenches.
yeah. trenches are too powerful. more than bunker in vanilina. i know ww1 was trench warfare but that is too powerful so german empire cant push enough.

2.crazy conscripition
ww1 was not greatest scale than ww2. which means, every countries dont have to get hundread armies. why france or india got 2-3m armies? we have to decrease armies through decreasing manpowers or make quips more expensive.

**Comment by MasterWaifuman** [comment]
>i know ww1 was trench warfare but that is too powerful so german empire cant push enough.

Actually, France has bunkers on german border. That's why i think GER can't push through it. Conscription for France, for example, is good. At the start it has pretty low manpower, but BEL has got pretty much manpower for such small country, but i am low manpower may not fix unit spam, so i'm fixing it through AI strategy.
