### ISSUE TITLE
Italo-Turkish War 

### ISSUE THREAD

**Issue by DevilIris** [Wolferos/Hearts-of-Iron-IV-The-Great-War#31]
I was testing the event but turkey always wins the war. Im trying to fix that, The script is fine,, 
(any suggestions?)

**Comment by Wolferos** [comment]
Hey

At the moment, the Italo-Turkish War looks like this:

- Italy and the Ottoman Empire must not be in a faction. Otherwise, there is a big risk that they call their allies.
- If one of the two countries join a Faction, the war shoud start because they may again call their allies
- The war ends if Italy is kicked out from Lybia (no more controlled states)
- The AI don't know how to correctly invade Lybia. Sometimes the AI stays at Tobrouk and launch many invasions in the south of Turkey
- The new OOB for the Ottoman Empire made them more powerfull than the reality (so we may revert this commit)
- Since we can't really stop a war properly because we can't get all the informations we need, we have to force things by code.

So yeah, this war is a bit tricky

**Comment by Wolferos** [comment]
Fixed in the 0.2
